encoding: UTF-8

highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
  syntax_highlighter: rouge

future: true
jailed: false

theme: jekyll-theme-primer
gfm_quirks: paragraph_end

lang: zh-CN

title: You Dont Know Java
description: ğŸ®â˜•ï¸ ä½ æ²¡è§è¿‡çš„ Java è¯­æ³•ï¼ˆè‡³ Java 8ï¼‰
